import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "DevAssistX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-background text-foreground antialiased !font-default overflow-x-hidden">
        {children}
      </body>
    </html>
  );
}
