import {
  ActivityIcon,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  BarChart3Icon,
  BookOpen,
  Bot,
  Brain,
  BugIcon,
  ClockIcon,
  Code2,
  FileTextIcon,
  GitBranchIcon,
  LayoutDashboardIcon,
  LoaderCircle,
  Network,
  SettingsIcon,
  Swords,
} from "lucide-react";
import { FaGithub } from "react-icons/fa";

export const Icons = {
  alertCircle: AlertCircle,
  bookOpen: BookOpen,
  code: Code2,
  clock: ClockIcon,
  logo: Swords,
  gitLogo: FaGithub,
  gitBranch: GitBranchIcon,
  gitBug: BugIcon,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  loader: LoaderCircle,
  activityLog: ActivityIcon,
  dashboard: LayoutDashboardIcon,
  loaderCircle: LoaderCircle,
  settings: SettingsIcon,
  barChart: BarChart3Icon,
  fileText: FileTextIcon,
  bot: Bot,
  networkGraph: Network,
  brainCircuit: Brain,
};
