import {
  AlertCircle,
  ArchiveRestore,
  ArrowRight,
  BookText,
  Check,
  ChevronDown,
  ChevronRight,
  Copyright,
  DollarSign,
  DotIcon,
  LogOut,
  MapPin,
  Menu,
  Moon,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Trash2,
  User,
  Zap,
} from "lucide-react";
import {
  FaDiscord,
  FaGithub,
  FaInstagram,
  FaLinkedin,
  FaSpinner,
  FaTelegramPlane,
  FaYoutube,
} from "react-icons/fa";
import { RiTwitterXFill } from "react-icons/ri";
const icons = {
  sparcle: Sparkles,
  rightarrow: ArrowRight,
  menu: Menu,
  dropdown: ChevronDown,
  twitter: RiTwitterXFill,
  youtube: FaYoutube,
  linkedin: FaLinkedin,
  github: FaGithub,
  discord: FaDiscord,
  instagram: FaInstagram,
  telergam: FaTelegramPlane,
  loading: FaSpinner,
  copyright: Copyright,
  sun: Sun,
  ArchiveRestore: ArchiveRestore,
  trash: Trash2,
  moon: Moon,
  check: Check,
  "chevron-right": ChevronRight,
  "dot-filled": DotIcon,
  location: MapPin,
  currency: DollarSign,
  description: BookText,
  profile: User,
  logout: LogOut,
  filter: SlidersHorizontal,
  alert: AlertCircle,
  zap: Zap,
};
export default icons;
