import {
  ArrowRightIcon,
  ChartCandlestick,
  Cog,
  HelpCircleIcon,
  LayoutGrid,
  LineChartIcon,
  Link2Icon,
  LoaderCircle,
  LockIcon,
  Menu,
  Merge,
  NewspaperIcon,
  QrCodeIcon,
  X,
  ZapIcon,
} from "lucide-react";

export const Icons = {
  help: HelpCircleIcon,
  chart: LineChartIcon,
  link: Link2Icon,
  lock: LockIcon,
  news: NewspaperIcon,
  qr: QrCodeIcon,
  zap: ZapIcon,
  logo: Merge,
  menu: Menu,
  close: X,
  next: ArrowRightIcon,
  spinner: LoaderCircle,
  chat: ChartCandlestick,
  settings: Cog,
  grid: LayoutGrid,
};
